exports.createCourseVideos = function() {
  Course_Video.create(
    {courseId: 'startup-001' , videoId: 1, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Startup Engineering [2:08]' , duration: 128 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part1-introduction%20%5B5c67f616%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Instructors [1:43]' , duration: 103 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part2-instructors%20%5B4ee98a88%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Motivation [1:56]' , duration: 116 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part3-motivation%20%5Ba558373b%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'},
    {courseId: 'startup-001' , videoId: 4, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Syllabus and Assignments [2:59]' , duration: 179 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part4-syllabus%20%5Bd2e81c75%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Final Project [5:00]' , duration: 300 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part5-final-project%20%5B9d0fc656%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Final Project Teams [1:23]' , duration: 83 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part6-final-project-teams%20%5B47276e27%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'},
    {courseId: 'startup-001' , videoId: 7, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Guest Lecturers, Meetups/Hackathons, and Summary [1:33]' , duration: 128 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part7-collab-summary%20%5Bdce04434%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 

    {courseId: 'startup-001' , videoId: 1, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'What is a Startup? [2:32]' , duration: 152 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part1-what-are-startups%20%5B33b88896%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Startups of the Past [7:15]' , duration: 435 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part2-startups-past%20%5B5f5387bd%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Startups of the Present [2:36]' , duration: 156 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part3-startups-present%20%5B0da5ff02%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 4, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Rise of the Internet Startup: Fall of the USSR [3:11]' , duration: 191 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part4-fall-of-ussr%20%5B7c49e540%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Rise of the Internet Startup: Repeal of the NSF AUP [2:58]' , duration: 178 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part5-nsf-aup-repeal%20%5B91138f14%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Key Features of Internet Startups [9:37]' , duration: 577 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part6-features-of-internet-startups%20%5B9e2e82c8%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 7, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Technological Trends: Mobility and Decentralization [6:18]' , duration: 378 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part7-mobility-decentralization%20%5B2bc69b95%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 8, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'What is Startup Engineering? [2:37]' , duration: 157 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part8-startup-engineering-tech%20%5B2c0505b2%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 9, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'The Importance of Versatility [3:06]' , duration: 186 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part9-design-marketing-sales-v2%281%29.51c34634c3d18.webm', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 10, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Design, Marketing, and Sales [1:05]' , duration: 75 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part10-versatility%20%5B848ffb83%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 11, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Mobile HTML5: Target Platform for the Final Project [4:38]' , duration: 278 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part11-mobile-html5%20%5B1140c3dc%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 



    function(err, data) {
              if (err) {
                return console.log('error in createing courses ' + err);
              } else {
                console.log('Refeernce data for course videos created successully');
              }
            });  
};