exports.createCourseVideos = function() {
  Course_Video.create(
    {courseId: 'startup-001' , videoId: 1, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Startup Engineering [2:08]' , duration: 128 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part1-introduction%20%5B5c67f616%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Instructors [1:43]' , duration: 103 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part2-instructors%20%5B4ee98a88%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Motivation [1:56]' , duration: 116 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part3-motivation%20%5Ba558373b%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'},
    {courseId: 'startup-001' , videoId: 4, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Syllabus and Assignments [2:59]' , duration: 179 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part4-syllabus%20%5Bd2e81c75%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Final Project [5:00]' , duration: 300 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part5-final-project%20%5B9d0fc656%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Final Project Teams [1:23]' , duration: 83 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part6-final-project-teams%20%5B47276e27%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'},
    {courseId: 'startup-001' , videoId: 7, groupId: 1, lectureGroup: 'Lecture 0: Logistics (Week 1)', videoName: 'Guest Lecturers, Meetups/Hackathons, and Summary [1:33]' , duration: 128 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture0-v2-part7-collab-summary%20%5Bdce04434%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 

    {courseId: 'startup-001' , videoId: 1, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'What is a Startup? [2:32]' , duration: 152 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part1-what-are-startups%20%5B33b88896%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Startups of the Past [7:15]' , duration: 435 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part2-startups-past%20%5B5f5387bd%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Startups of the Present [2:36]' , duration: 156 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part3-startups-present%20%5B0da5ff02%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 4, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Rise of the Internet Startup: Fall of the USSR [3:11]' , duration: 191 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part4-fall-of-ussr%20%5B7c49e540%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Rise of the Internet Startup: Repeal of the NSF AUP [2:58]' , duration: 178 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part5-nsf-aup-repeal%20%5B91138f14%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Key Features of Internet Startups [9:37]' , duration: 577 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part6-features-of-internet-startups%20%5B9e2e82c8%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 7, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Technological Trends: Mobility and Decentralization [6:18]' , duration: 378 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part7-mobility-decentralization%20%5B2bc69b95%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 8, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'What is Startup Engineering? [2:37]' , duration: 157 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part8-startup-engineering-tech%20%5B2c0505b2%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 9, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'The Importance of Versatility [3:06]' , duration: 186 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part9-design-marketing-sales-v2%281%29.51c34634c3d18.webm', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 10, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Design, Marketing, and Sales [1:05]' , duration: 75 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part10-versatility%20%5B848ffb83%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 11, groupId: 2, lectureGroup: 'Lecture 1: Introduction (Week 1)', videoName: 'Mobile HTML5: Target Platform for the Final Project [4:38]' , duration: 278 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture1-part11-mobile-html5%20%5B1140c3dc%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 

    {courseId: 'startup-001' , videoId: 1, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Your First Web Application [2:56]' , duration: 176 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part1-your-first-webapp%281%29.51c322c698aa6.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'OS X: Command Line via Terminal.app [2:02]' , duration: 122 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part2-mac-terminal%20%5B4c762ca5%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Windows: Command Line via Cygwin [1:28]' , duration: 88 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part3-windows-terminal%20%5Be8e697ad%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 4, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Amazon Web Services (AWS) Signup [2:39]' , duration: 159 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part4-aws-signup%20%5B26f40c12%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Github, Gravatar, Heroku Signup [2:38]' , duration: 158 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part5-github-gravatar-heroku%20%5B8de93161%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Launching your first EC2 Instance [4:54]' , duration: 294 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part6-initialize-aws%20%5Be02044e4%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 7, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'OS X: Connect to EC2 instance via Terminal.app [1:46]' , duration: 106 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part7-ec2-mac%20%5Bff55ff3e%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 8, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Windows: Connect to EC2 instance via Cygwin [2:36]' , duration: 156 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part8-ec2-win%20%5B93b036fc%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 9, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'EC2 Security Groups and SSH / Port 22 [1:36]' , duration: 96 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part9-security-groups%20%5B9ca7cb4f%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 10, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Our New Standard Environment: Ubuntu 12.04.2 LTS on AWS EC2 [2:43]' , duration: 163 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part10-remote-vs-local%20%5B64fc3850%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 11, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Deploying your first node.js app on Heroku [4:18]' , duration: 258 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part11-heroku-deploy%20%5B6a41a83d%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 12, groupId: 3, lectureGroup: 'Lecture 2: Interactive Start (Week 1)', videoName: 'Recap / Summary: Your First Web Application [2:12]' , duration: 132 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture2-part12-summary%20%5B893b5157%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 

    {courseId: 'startup-001' , videoId: 1, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Linux: Overview and Key Features [4:39]' , duration: 279 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part1-overview-key-features%20%5B6f785e3a%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Virtual Machines [1:06]' , duration: 66 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part2-vms%20%5Bf4434a9e%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'The Cloud (IAAS/PAAS/SAAS) [0:59]' , duration: 59 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part3-cloud-iaas-paas-saas%20%5B78bac92f%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 4, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Linux Basics [1:10]' , duration: 70 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part4-linux-basics%20%5Bc069c34b%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Filesystem Basics [4:20]' , duration: 260 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part5-filesystem-basics%20%5B8dcac063%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Env, PATH, and HOME [2:09]' , duration: 129 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part6-env-path-home%20%5B81563a5a%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 7, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Debugging PATH issues with Which [3:40]' , duration: 220 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part7-which-path-debug%20%5B8a0d2ac7%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 8, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'SSH [2:54]' , duration: 174 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part8-ssh%20%5B074cf74c%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 9, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'SCP [1:50]' , duration: 110 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part9-scp%20%5Ba4ba71a5%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 10, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Basic Bash [1:04]' , duration: 64 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part10-bash%20%5Bb76db3de%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 11, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Installing Node and Npm [3:23]' , duration: 203 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part11-node-npm%20%5Bf76b5049%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 12, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Editing with Nano; Hello World with Node [2:01]' , duration: 121 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part12-editing-hello%20%5B4102fb06%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 13, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Second Node Program: Using the Libraries [1:08]' , duration: 68 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part13-hello2%20%5B8b85fbc1%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 
    {courseId: 'startup-001' , videoId: 14, groupId: 4, lectureGroup: 'Lecture 3: Linux and Server-Side Javascript (Week 2)', videoName: 'Third Node Program: Fibonacci Numbers [2:34]' , duration: 154 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture3-v2-part14-fibonacci%20%5B4202e7c4%5D%20.mp4', flashSupported: false, html5Supported: true, format: 'mp4'}, 

    {courseId: 'startup-001' , videoId: 1, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Introduction and References [0:32]' , duration: 32 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part1-intro.51d19cf5c052a.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'STDIN, STDOUT, and STDERR [4:55]' , duration: 295 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part2-stdin-stdout-stderr.51d19cfec9dec.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Navigation and Filesystem [1:56]' , duration: 116 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part3-navigation-filesystem.51d19d08169b2.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 4, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Downloading and Syncing [3:08]' , duration: 188 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part4-downloading-syncing.51d19d1b167b2.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Basic Text Processing [11:41]' , duration: 701 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part5-basic-text-processing.51d19d4a3afb6.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Help, System, and Process Information [3:06]' , duration: 186 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part6-help-system-process.51d19d54e26a5.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 7, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Superuser [1:06]' , duration: 66 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part7-superuser.51d19d5c57918.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 8, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Storage and Location [2:13]' , duration: 133 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part8-storage-location.51d19d63566fe.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 9, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Intermediate Text Processing [4:46]' , duration: 286 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part9-intermediate-text-processing.51d19d6d5a0c0.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 10, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Bash Keyboard Shortcuts [3:46]' , duration: 226 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part10-bash-keyboard-shortcuts.51d19d740dd0c.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 11, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Intermediate Bash [2:38]' , duration: 158 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part11-intermediate-bash.51d19d7beb516.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 12, groupId: 5, lectureGroup: 'Lecture 4a: The Linux Command Line (Week 2/3)', videoName: 'Summary [1:09]' , duration: 69 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4a-part12-summary%281%29.51d1eb0570b60.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 

    {courseId: 'startup-001' , videoId: 1, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Introduction [1:05]' , duration: 65 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part1-introduction.51d350e6e493a.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 2, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Screen: Tabs and Navigation [3:53]' , duration: 233 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part2-screen-motivation%281%29.51d3620ca4082.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 3, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Screen: Copy and Paste [4:12]' , duration: 252 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part3-screen-tabs-navigation%281%29.51d36239079ce.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 4, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Screen: Detach and Reattach Sessions [1:25]' , duration: 85 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part4-screen-copy-paste.51d35105c868a.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 5, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: A Text Editor [1:57]' , duration: 117 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part5-screen-detach-reattach%281%29.51d3624adba7c.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 6, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: Control and Meta for OSX and Windows [3:40]' , duration: 220 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part6-emacs-intro.51d35114ea570.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 8, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: Installation [2:25]', duration: 145 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part7-emacs-control-meta%281%29.51d364d9df049.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 9, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: Built-in Tutorial [1:55]' , duration: 115 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part8-emacs-install-setup%281%29.51d364e1a7842.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 10, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: Editing SSJS and REPL Integration [4:51]' , duration: 291 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part9-emacs-help-with-tutorial%281%29.51d364edaf56a.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 11, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: Debugging SSJS and JSHint [2:09]' , duration: 129 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part10-emacs-repl%281%29.51d364f5bbf18.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 12, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: Summary [1:28]' , duration: 88 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part11-emacs-jshint%281%29.51d364fe10584.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 13, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Git: Distributed Version Control System [2:51]' , duration: 171 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part12-emacs-summary%281%29.51d36571bb512.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 14, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Git: The SHA1 hash function [3:49]' , duration: 229 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part13-git-dvcs%281%29.51d367dd47a04.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 15, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Git: A sample session [8:21]' , duration: 501 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part14-git-sha1%281%29.51d367e4b791f.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 16, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Git: Pushing code to Github [6:30]' , duration: 390 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part15-git-session%281%29.51d367ecc7163.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 17, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Devops Basics: Setup.git and Dotfiles.git [6:13]' , duration: 373 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part16-git-pushing-to-github%281%29.51d367f3e7805.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    {courseId: 'startup-001' , videoId: 7, groupId: 6, lectureGroup: 'Lecture 4b: Linux Development Environment (Week 2/3)', videoName: 'Emacs: Installation [2:25]' , duration: 145 , url: 'http://d396qusza40orc.cloudfront.net/startup/recoded_videos%2Flecture4b-part17-setup-dotfiles%281%29.51d367faa94bf.webm', flashSupported: false, html5Supported: true, format: 'webm'}, 
    




    function(err, data) {
              if (err) {
                return console.log('error in createing courses ' + err);
              } else {
                console.log('Refeernce data for course videos created successully');
              }
            });  
};